# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJSnkjY0cdZpoj1jjEPG2hH5yFg93IER
"""

#!pip install cadquery pyvista trimesh

# ============================================================
# DfM Agent — Automatic Parting Line Detection
# RB-CoC Plastics Hackathon | Level 1
# ============================================================

# ── CELL 1: Install dependencies ────────────────────────────
# !pip install cadquery trimesh networkx plotly scipy

# ── CELL 2: Imports ─────────────────────────────────────────
import numpy as np
import trimesh
import networkx as nx
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.spatial import cKDTree
import cadquery as cq

# ── CELL 3: Load STEP + tessellate ──────────────────────────
STEP_FILE = "Part1.stp"          # ← change to Part2.stp for Level 2

part = cq.importers.importStep(STEP_FILE)
vertices, triangles = part.val().tessellate(0.5)

verts = np.array([[v.x, v.y, v.z] for v in vertices])
mesh  = trimesh.Trimesh(vertices=verts, faces=np.array(triangles))

print(f"Loaded: {STEP_FILE}")
print(f"Faces   : {len(mesh.faces):,}")
print(f"Vertices: {len(mesh.vertices):,}")

# ── CELL 4: Auto mold direction ─────────────────────────────
directions = {
    "+X": np.array([1,0,0]),  "-X": np.array([-1,0,0]),
    "+Y": np.array([0,1,0]),  "-Y": np.array([0,-1,0]),
    "+Z": np.array([0,0,1]),  "-Z": np.array([0,0,-1]),
}

undercut_counts = {}
for name, d in directions.items():
    undercut_counts[name] = int(np.sum(np.dot(mesh.face_normals, d) < 0))
    print(f"  {name} → undercuts: {undercut_counts[name]}")

best_name   = min(undercut_counts, key=undercut_counts.get)
pull_vector = directions[best_name]
print(f"\nBest mold direction: {best_name}  ({undercut_counts[best_name]} undercuts)")

# ── CELL 5: Classify faces + DfM score ──────────────────────
dot_products = np.dot(mesh.face_normals, pull_vector)
total        = len(dot_products)

safe     = int(np.sum(dot_products >  0.2))
warning  = int(np.sum((dot_products >= 0) & (dot_products <= 0.2)))
undercut = int(np.sum(dot_products <  0))

# 0 = cavity (faces mold opening side), 1 = core (faces away)
face_class = np.where(dot_products >= 0, 0, 1)

score = max(0.0, min(100.0,
    safe/total*100 - undercut/total*40 - warning/total*20
))

print(f"Safe    : {safe:,}  ({safe/total*100:.1f}%)")
print(f"Warning : {warning:,}  ({warning/total*100:.1f}%)")
print(f"Undercut: {undercut:,}  ({undercut/total*100:.1f}%)")
print(f"DfM Score: {round(score, 1)} / 100")

# ── CELL 6: Parting edge detection ──────────────────────────
# Step A — sign-change adjacency: edges where cavity meets core
adjacency       = mesh.face_adjacency           # (N,2) face index pairs
adjacency_edges = mesh.face_adjacency_edges     # (N,2) shared vertex indices

d1 = dot_products[adjacency[:, 0]]
d2 = dot_products[adjacency[:, 1]]
sign_change_mask   = (d1 * d2) < 0
parting_edge_verts = adjacency_edges[sign_change_mask]

edge_midpoints = (
    mesh.vertices[parting_edge_verts[:, 0]] +
    mesh.vertices[parting_edge_verts[:, 1]]
) / 2

print(f"Raw parting edges (sign-change): {len(parting_edge_verts):,}")

# Step B — keep only edges perpendicular to pull direction
# (parting line edges run horizontal, not along the walls)
v0 = mesh.vertices[parting_edge_verts[:, 0]]
v1 = mesh.vertices[parting_edge_verts[:, 1]]
edge_vec  = v1 - v0
edge_norm = edge_vec / (np.linalg.norm(edge_vec, axis=1, keepdims=True) + 1e-10)
alignment = np.abs(np.dot(edge_norm, pull_vector))

PERP_THRESH = 0.4                              # lower = stricter horizontal filter
perp_mask   = alignment < PERP_THRESH
perp_edges  = parting_edge_verts[perp_mask]
perp_mids   = edge_midpoints[perp_mask]

print(f"Perpendicular parting edges: {len(perp_edges):,}")

# ── CELL 7: Group outer vs inner loops ──────────────────────
NOISE_MIN_VERTS  = 15    # drop components smaller than this (noise)
OUTER_RADIUS_MIN = 8.0   # XY radius threshold: outer wall vs inner features

G = nx.Graph()
G.add_edges_from(perp_edges.tolist())
components = sorted(nx.connected_components(G), key=len, reverse=True)
print(f"Connected components: {len(components)}")

outer_loops, inner_loops = [], []
for c in components:
    if len(c) < NOISE_MIN_VERTS:
        continue
    verts_xyz = mesh.vertices[list(c)]
    avg_r = np.sqrt(verts_xyz[:,0]**2 + verts_xyz[:,1]**2).mean()
    z_mean = verts_xyz[:,2].mean()
    if avg_r > OUTER_RADIUS_MIN:
        outer_loops.append(c)
    else:
        inner_loops.append(c)

def get_edges_for_components(comp_list, edge_array):
    all_verts = set()
    for c in comp_list:
        all_verts |= c
    if not all_verts:
        return np.empty((0,2), dtype=int)
    return np.array([e for e in edge_array
                     if e[0] in all_verts and e[1] in all_verts])

def edges_to_xyz(edges, vertices):
    px, py, pz = [], [], []
    for v0, v1 in edges:
        p0, p1 = vertices[v0], vertices[v1]
        px += [p0[0], p1[0], None]
        py += [p0[1], p1[1], None]
        pz += [p0[2], p1[2], None]
    return px, py, pz

outer_final = get_edges_for_components(outer_loops, perp_edges)
inner_final = get_edges_for_components(inner_loops, perp_edges)

print(f"Outer boundary loops: {len(outer_loops)}  ({len(outer_final)} edges)")
print(f"Inner feature loops : {len(inner_loops)}  ({len(inner_final)} edges)")

# ── CELL 8: Final visualization + export ────────────────────
fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type":"scene"}, {"type":"scene"}]],
    subplot_titles=["Parting line view", "Core / cavity split"]
)

# Left panel — gray mesh + parting lines
fig.add_trace(go.Mesh3d(
    x=mesh.vertices[:,0], y=mesh.vertices[:,1], z=mesh.vertices[:,2],
    i=mesh.faces[:,0], j=mesh.faces[:,1], k=mesh.faces[:,2],
    color='lightgray', opacity=0.25, name="Mesh", showlegend=True
), row=1, col=1)

if len(outer_final):
    ox, oy, oz = edges_to_xyz(outer_final, mesh.vertices)
    fig.add_trace(go.Scatter3d(
        x=ox, y=oy, z=oz, mode='lines',
        line=dict(color='gold', width=6),
        name=f'Outer parting line ({len(outer_final)} edges)'
    ), row=1, col=1)

if len(inner_final):
    ix, iy, iz = edges_to_xyz(inner_final, mesh.vertices)
    fig.add_trace(go.Scatter3d(
        x=ix, y=iy, z=iz, mode='lines',
        line=dict(color='cyan', width=4),
        name=f'Inner parting loops ({len(inner_final)} edges)'
    ), row=1, col=1)

# Right panel — core/cavity colored mesh + parting lines
fig.add_trace(go.Mesh3d(
    x=mesh.vertices[:,0], y=mesh.vertices[:,1], z=mesh.vertices[:,2],
    i=mesh.faces[:,0], j=mesh.faces[:,1], k=mesh.faces[:,2],
    intensity=face_class,
    colorscale=[[0,"royalblue"],[1,"tomato"]],
    showscale=True,
    colorbar=dict(title="Surface", tickvals=[0,1],
                  ticktext=["Cavity","Core"], len=0.4, x=1.02),
    opacity=0.5, name="Core / Cavity", showlegend=True
), row=1, col=2)

if len(outer_final):
    ox2, oy2, oz2 = edges_to_xyz(outer_final, mesh.vertices)
    fig.add_trace(go.Scatter3d(
        x=ox2, y=oy2, z=oz2, mode='lines',
        line=dict(color='gold', width=5), showlegend=False
    ), row=1, col=2)

if len(inner_final):
    ix2, iy2, iz2 = edges_to_xyz(inner_final, mesh.vertices)
    fig.add_trace(go.Scatter3d(
        x=ix2, y=iy2, z=iz2, mode='lines',
        line=dict(color='cyan', width=4), showlegend=False
    ), row=1, col=2)

fig.update_layout(
    title=dict(
        text=(
            f"<b>DfM Agent — {STEP_FILE}</b><br>"
            f"<sup>Mold dir: {best_name} (auto) | "
            f"Score: {round(score,1)}/100 | "
            f"Safe: {safe/total*100:.1f}% | "
            f"Warning: {warning/total*100:.1f}% | "
            f"Undercut: {undercut/total*100:.1f}% | "
            f"Parting: stepped multi-level</sup>"
        ),
        x=0.5
    ),
    scene=dict(aspectmode='data'),
    scene2=dict(aspectmode='data'),
    height=620,
    legend=dict(x=0, y=1)
)

fig.show()

out_html = STEP_FILE.replace(".stp", "_DfM_Result.html")
fig.write_html(out_html)

print("\n" + "="*45)
print("  DfM ANALYSIS SUMMARY")
print("="*45)
print(f"  Part            : {STEP_FILE}")
print(f"  Mold direction  : {best_name}  (auto-selected)")
print(f"  DfM Score       : {round(score,1)} / 100")
print(f"  Safe faces      : {safe:,} ({safe/total*100:.1f}%)")
print(f"  Warning faces   : {warning:,} ({warning/total*100:.1f}%)")
print(f"  Undercut faces  : {undercut:,} ({undercut/total*100:.1f}%)")
print(f"  Parting type    : Stepped (multi-level)")
print(f"  Outer loops     : {len(outer_loops)} loops, {len(outer_final)} edges")
print(f"  Inner loops     : {len(inner_loops)} loops, {len(inner_final)} edges")
print(f"  Total PL edges  : {len(outer_final)+len(inner_final)}")
print(f"  Output saved    : {out_html}")
print("="*45)

